version: "3.9"
services:
  ems-postgres:
    container_name: ems-postgres
    image: prasetyaip/ems-postgresql:v1
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_DB=DBNAME
    networks:
      - ems_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ems-apiserver:
    container_name: ems-apiserver
    image: prasetyaip/ems-aquadev:v3
    ports:
      - "1323:1323"
    environment:
      - DB_HOST=HOST
      - DB_USER=USER
      - DB_PASSWORD=PASSWORD
      - DB_NAME=DBNAME
      - DB_PORT=PORT
      - DB_TIMEZONE=TIMEZONE
      - JWT_SECRET=SECRET
    networks:
      - ems_network
    depends_on:
      ems-postgres:
        condition: service_healthy
networks:
  ems_network:
    name: ems_network
